Stack S;
createStack(S);
pushAscending(S, 3);
pushAscending(S, 4);
pushAscending(S, 8);
pushAscending(S, 2);
pushAscending(S, 3);
pushAscending(S, 9);
printInfo(S);
cout << "Balik stack:" << endl;
balikStack(S);
printInfo(S);
